version: "3"

services:
  mongo-service:
    container_name: mongo-service
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPasXw0r
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    restart: on-failure
    ports:
      - 27017:27017
    command:
      - mongod
  web-service:
    container_name: solink-web-service-app
    build: 
      context: .
      dockerfile: ./dockerfile
    command: node app.js
    # environment:
    #   - DATABASE_HOST=db
    ports:
      - 3001:3001
    depends_on:
      - mongo-service
    volumes:
      - ./:/usr/src/app
volumes:
  mongodb-data:
