FROM node:12.20.0

LABEL version="1.0"
LABEL description="So . Link"

WORKDIR /usr/src/app

COPY ./package*.json ./
RUN npm cache clean --force && npm install
COPY . .

EXPOSE 3001
CMD [ "npm", "run", "start" ]